// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-gem: https://img.shields.io/gem/v/pls?color=dfaf8f&labelColor=555555&logo=rubygems&logoColor=dcdccc&style=flat
:img-hoc: https://hitsofcode.com/github/rdavid/pls?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/pls?color=8cd0d3&labelColor=555555&logo=freebsd&logoColor=dcdccc&style=flat
:img-rake: https://img.shields.io/github/actions/workflow/status/rdavid/pls/rake.yml?branch=master&label=rake&color=7f9f7f&labelColor=555555&logo=github&logoColor=dcdccc&style=flat
:img-rubocop: https://img.shields.io/github/actions/workflow/status/rdavid/pls/rubocop.yml?branch=master&label=rubocop&color=93e0e3&labelColor=555555&logo=github&logoColor=dcdccc&style=flat
:img-style: https://img.shields.io/badge/code_style-rubocop-7f9f7f.svg?labelColor=555555
:url-cv: http://cv.rabkin.co.il
:url-gem: https://badge.fury.io/rb/pls
:url-hoc: https://hitsofcode.com/view/github/rdavid/pls?branch=master
:url-license: https://github.com/rdavid/pls/blob/master/LICENSES/0BSD.txt
:url-rake: https://github.com/rdavid/pls/actions/workflows/rake.yml
:url-reuse: https://github.com/fsfe/reuse-action
:url-rubocop: https://github.com/rdavid/pls/actions/workflows/rubocop.yml
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-style: https://github.com/rubocop/rubocop
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Package Lister

[subs=attributes+]
++++
<div align="right">
<a href="{url-rake}"><img src="{img-rake}" alt="rake"></a>
<a href="{url-rubocop}"><img src="{img-rubocop}" alt="rubocop"></a>
<a href="{url-gem}"><img src="{img-gem}" alt="gem version"></a>
<a href="{url-style}"><img src="{img-style}" alt="code style"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/pls" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About
Package Lister prints the full dependency tree of a given NodeJS package.
NodeJS developers rely on packages: modules published with their own
version, documentation, and dependencies on other packages.
npm, NodeJS's package manager, gains new packages and new versions of
existing ones every day.
Given a package name, the tool fetches its complete set of dependencies
from npm.

== Installation
The tool works on macOS, GNU/Linux, other Unix-like operating systems, and
Windows.
It is packaged as a gem and requires Ruby 3.2 or later.
If you don't have the required Ruby version, see {url-ruby}[Installing
Ruby].

Use this command to install:

[,sh]
----
    gem install pls
----

== Updating
Use this command to update the package:

[,sh]
----
    gem update pls
----

== Usage

[,sh]
----
    pls [options]
      -p, --pac package                Package name.
      -v, --version                    Show version.
----

== Example

[,sh]
----
    pls -p express
----

ifdef::pages-build[]
++++
<div id="term-demo">
  <div class="window">
    <div class="titlebar">
      <div class="dots">
        <span class="dot red"></span>
        <span class="dot yellow"></span>
        <span class="dot green"></span>
      </div>
      <span class="tab">bin/pls &mdash; pls -p express</span>
    </div>
    <div class="term-body">
      <div class="row">
        <span class="gutter"><span class="badge">1</span></span>
        <span class="prompt"><span class="sym">$</span> pls -p express</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">express</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;accepts</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;&#32;&#32;mime-types</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">2</span></span>
        <span class="pkg">&#32;&#32;&#32;&#32;&#32;&#32;mime-db</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;&#32;&#32;negotiator</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">3</span></span>
        <span class="pkg">&#32;&#32;body-parser</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;&#32;&#32;debug</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;&#32;&#32;&#32;&#32;ms</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;&#32;&#32;qs</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;send</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">4</span></span>
        <span class="pkg cached">&#32;&#32;&#32;&#32;mime-types</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="pkg">&#32;&#32;&#32;&#32;fresh</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">5</span></span>
        <span class="ok">Done in 2 seconds.</span>
      </div>
    </div>
  </div>
  <div class="legend">
    <h3>What the numbers point at</h3>
    <ol>
      <li>
        <span class="num">1</span>
        <p>No subcommands to learn &mdash; a single <code>-p</code> flag prints the whole tree to stdout.</p>
      </li>
      <li>
        <span class="num">2</span>
        <p>Every dependency is indented two spaces per depth level, drawn by <code>Reporter#out</code>'s recursive <code>del + 2</code> calls.</p>
      </li>
      <li>
        <span class="num">3</span>
        <p><code>accepts</code>, <code>body-parser</code>, and <code>send</code> are express's direct dependencies &mdash; <code>Pls#build_dep</code> spawns one thread per key, so all three resolve concurrently.</p>
      </li>
      <li>
        <span class="num">4</span>
        <p><code>mime-types</code> shows up under both <code>accepts</code> and <code>send</code>, but <code>Pls#build</code> only calls the npm registry for it once &mdash; the second line comes straight from the in-memory cache.</p>
      </li>
      <li>
        <span class="num">5</span>
        <p>The only line <code>Reporter#do</code> adds after the tree &mdash; total wall-clock time for the run.</p>
      </li>
    </ol>
  </div>
</div>
++++
endif::[]

ifndef::pages-build[]
[,sh]
----
express
  accepts
    mime-types
      mime-db
    negotiator
  body-parser
    debug
      ms
    qs
  send
    mime-types
    fresh
Done in 2 seconds.
----
endif::[]

== License
`pls` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>pls by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/pls" target="_blank" rel="noopener">GitHub</a>
    <a href="https://rubygems.org/gems/pls" target="_blank" rel="noopener">RubyGems</a>
    <a href="https://github.com/rdavid/pls/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
